export const products: Product[] = [
  {
    id: "prod-001",
    name: "Wireless Noise Cancelling Headphones",
    brand: "SoundWave",
    price: 299.99,
    discountPrice: 249.99,
    images: ["https://picsum.photos/seed/headphones1/600/600", "https://picsum.photos/seed/headphones2/600/600"],
    rating: 4.8,
    reviewCount: 1240,
    stock: 45,
    category: "Electronics",
    description: "",
    specifications: {},
  },
  {
    id: "prod-002",
    name: "Ergonomic Office Chair",
    brand: "SitRight",
    price: 450.00,
    images: ["https://picsum.photos/seed/chair1/600/600"],
    rating: 4.5,
    reviewCount: 830,
    stock: 12,
    category: "Furniture",
    description: "",
    specifications: {},
  },
  {
    id: "prod-003",
    name: "Organic Green Tea Set",
    brand: "Leaf & Brew",
    price: 34.99,
    discountPrice: 29.99,
    images: ["https://picsum.photos/seed/tea1/600/600", "https://picsum.photos/seed/tea2/600/600"],
    rating: 4.9,
    reviewCount: 2100,
    stock: 150,
    category: "Grocery",
    description: "",
    specifications: {},
  },
  {
    id: "prod-004",
    name: "Running Shoes Pro",
    brand: "Velocity",
    price: 129.99,
    images: ["https://picsum.photos/seed/shoes1/600/600", "https://picsum.photos/seed/shoes2/600/600", "https://picsum.photos/seed/shoes3/600/600"],
    rating: 4.6,
    reviewCount: 560,
    stock: 30,
    category: "Sports",
    description: "",
    specifications: {},
  },
  {
    id: "prod-005",
    name: "Smart Fitness Watch",
    brand: "TechFit",
    price: 199.99,
    discountPrice: 179.99,
    images: ["https://picsum.photos/seed/watch1/600/600"],
    rating: 4.3,
    reviewCount: 920,
    stock: 60,
    category: "Electronics",
    description: "",
    specifications: {},
  },
  {
    id: "prod-006",
    name: "Stainless Steel Water Bottle",
    brand: "HydroLife",
    price: 24.99,
    images: ["https://picsum.photos/seed/bottle1/600/600"],
    rating: 4.7,
    reviewCount: 3400,
    stock: 200,
    category: "Home & Kitchen",
    description: "",
    specifications: {},
  },
  {
    id: "prod-007",
    name: "Mechanical Gaming Keyboard",
    brand: "ClickMaster",
    price: 149.99,
    images: ["https://picsum.photos/seed/kb1/600/600", "https://picsum.photos/seed/kb2/600/600"],
    rating: 4.8,
    reviewCount: 780,
    stock: 25,
    category: "Electronics",
    description: "",
    specifications: {},
  },
  {
    id: "prod-008",
    name: "Ceramic Coffee Mug Set",
    brand: "Artisan Home",
    price: 45.00,
    discountPrice: 38.00,
    images: ["https://picsum.photos/seed/mugs1/600/600"],
    rating: 4.4,
    reviewCount: 310,
    stock: 40,
    category: "Home & Kitchen",
    description: "",
    specifications: {},
  },
  {
    id: "prod-009",
    name: "Yoga Mat Premium",
    brand: "ZenFlex",
    price: 59.99,
    images: ["https://picsum.photos/seed/yogamat1/600/600"],
    rating: 4.6,
    reviewCount: 1100,
    stock: 75,
    category: "Sports",
    description: "",
    specifications: {},
  },
  {
    id: "prod-010",
    name: "Portable Bluetooth Speaker",
    brand: "BoomBox",
    price: 79.99,
    discountPrice: 69.99,
    images: ["https://picsum.photos/seed/speaker1/600/600", "https://picsum.photos/seed/speaker2/600/600"],
    rating: 4.5,
    reviewCount: 2300,
    stock: 55,
    category: "Electronics",
    description: "",
    specifications: {},
  },
  {
    id: "prod-011",
    name: "Leather Crossbody Bag",
    brand: "Urban Carry",
    price: 89.99,
    images: ["https://picsum.photos/seed/bag1/600/600", "https://picsum.photos/seed/bag2/600/600"],
    rating: 4.7,
    reviewCount: 420,
    stock: 18,
    category: "Fashion",
    description: "",
    specifications: {},
  },
  {
    id: "prod-012",
    name: "LED Desk Lamp",
    brand: "BrightSpace",
    price: 49.99,
    discountPrice: 39.99,
    images: ["https://picsum.photos/seed/lamp1/600/600"],
    rating: 4.4,
    reviewCount: 670,
    stock: 90,
    category: "Home & Kitchen",
    description: "",
    specifications: {},
  },
  {
    id: "prod-013",
    name: "Protein Powder Vanilla",
    brand: "NutriMax",
    price: 54.99,
    images: ["https://picsum.photos/seed/protein1/600/600"],
    rating: 4.2,
    reviewCount: 1500,
    stock: 100,
    category: "Health",
    description: "",
    specifications: {},
  },
  {
    id: "prod-014",
    name: "Wireless Charging Pad",
    brand: "ChargeFast",
    price: 29.99,
    images: ["https://picsum.photos/seed/charger1/600/600"],
    rating: 4.3,
    reviewCount: 890,
    stock: 120,
    category: "Electronics",
    description: "",
    specifications: {},
  },
  {
    id: "prod-015",
    name: "Bamboo Cutting Board Set",
    brand: "EcoKitchen",
    price: 39.99,
    discountPrice: 34.99,
    images: ["https://picsum.photos/seed/cuttingboard1/600/600", "https://picsum.photos/seed/cuttingboard2/600/600"],
    rating: 4.8,
    reviewCount: 540,
    stock: 65,
    category: "Home & Kitchen",
    description: "",
    specifications: {},
  },
  {
    id: "prod-016",
    name: "Denim Jacket Classic",
    brand: "ThreadWorks",
    price: 79.99,
    images: ["https://picsum.photos/seed/jacket1/600/600", "https://picsum.photos/seed/jacket2/600/600"],
    rating: 4.5,
    reviewCount: 290,
    stock: 22,
    category: "Fashion",
    description: "",
    specifications: {},
  },
  {
    id: "prod-017",
    name: "Noise Isolating Earbuds",
    brand: "SoundWave",
    price: 89.99,
    discountPrice: 74.99,
    images: ["https://picsum.photos/seed/earbuds1/600/600"],
    rating: 4.4,
    reviewCount: 1800,
    stock: 80,
    category: "Electronics",
    description: "",
    specifications: {},
  },
  {
    id: "prod-018",
    name: "Resistance Bands Set",
    brand: "FitGear",
    price: 24.99,
    images: ["https://picsum.photos/seed/bands1/600/600"],
    rating: 4.6,
    reviewCount: 2200,
    stock: 150,
    category: "Sports",
    description: "",
    specifications: {},
  },
  {
    id: "prod-019",
    name: "Scented Candle Lavender",
    brand: "Glow & Scent",
    price: 19.99,
    images: ["https://picsum.photos/seed/candle1/600/600"],
    rating: 4.7,
    reviewCount: 980,
    stock: 200,
    category: "Home & Kitchen",
    description: "",
    specifications: {},
  },
  {
    id: "prod-020",
    name: "Laptop Backpack Waterproof",
    brand: "Urban Carry",
    price: 69.99,
    discountPrice: 59.99,
    images: ["https://picsum.photos/seed/backpack1/600/600", "https://picsum.photos/seed/backpack2/600/600"],
    rating: 4.6,
    reviewCount: 710,
    stock: 35,
    category: "Fashion",
    description: "",
    specifications: {},
  },
  {
    id: "prod-021",
    name: "Electric Toothbrush",
    brand: "OralCare",
    price: 79.99,
    images: ["https://picsum.photos/seed/toothbrush1/600/600"],
    rating: 4.5,
    reviewCount: 3100,
    stock: 45,
    category: "Health",
    description: "",
    specifications: {},
  },
  {
    id: "prod-022",
    name: "Cast Iron Skillet 12\"",
    brand: "IronChef",
    price: 44.99,
    images: ["https://picsum.photos/seed/skillet1/600/600", "https://picsum.photos/seed/skillet2/600/600"],
    rating: 4.9,
    reviewCount: 4500,
    stock: 30,
    category: "Home & Kitchen",
    description: "",
    specifications: {},
  },
  {
    id: "prod-023",
    name: "UV Protection Sunglasses",
    brand: "ShadeStyle",
    price: 119.99,
    discountPrice: 99.99,
    images: ["https://picsum.photos/seed/sunglasses1/600/600"],
    rating: 4.3,
    reviewCount: 380,
    stock: 50,
    category: "Fashion",
    description: "",
    specifications: {},
  },
  {
    id: "prod-024",
    name: "USB-C Hub Multiport",
    brand: "ConnectAll",
    price: 39.99,
    images: ["https://picsum.photos/seed/hub1/600/600"],
    rating: 4.4,
    reviewCount: 1200,
    stock: 110,
    category: "Electronics",
    description: "",
    specifications: {},
  },
  {
    id: "prod-025",
    name: "Foam Roller Recovery",
    brand: "ZenFlex",
    price: 34.99,
    images: ["https://picsum.photos/seed/roller1/600/600"],
    rating: 4.5,
    reviewCount: 890,
    stock: 70,
    category: "Sports",
    description: "",
    specifications: {},
  },
  {
    id: "prod-026",
    name: "Multivitamin Daily Complex",
    brand: "NutriMax",
    price: 29.99,
    discountPrice: 24.99,
    images: ["https://picsum.photos/seed/vitamins1/600/600"],
    rating: 4.6,
    reviewCount: 2700,
    stock: 180,
    category: "Health",
    description: "",
    specifications: {},
  },
  {
    id: "prod-027",
    name: "Linen Throw Blanket",
    brand: "CozyNest",
    price: 64.99,
    images: ["https://picsum.photos/seed/blanket1/600/600", "https://picsum.photos/seed/blanket2/600/600"],
    rating: 4.8,
    reviewCount: 450,
    stock: 28,
    category: "Home & Kitchen",
    description: "",
    specifications: {},
  },
  {
    id: "prod-028",
    name: "Action Camera 4K",
    brand: "AdventureCam",
    price: 249.99,
    discountPrice: 219.99,
    images: ["https://picsum.photos/seed/camera1/600/600", "https://picsum.photos/seed/camera2/600/600"],
    rating: 4.4,
    reviewCount: 620,
    stock: 15,
    category: "Electronics",
    description: "",
    specifications: {},
  },
  {
    id: "prod-029",
    name: "Canvas Sneakers Unisex",
    brand: "StreetStep",
    price: 49.99,
    images: ["https://picsum.photos/seed/sneakers1/600/600", "https://picsum.photos/seed/sneakers2/600/600"],
    rating: 4.3,
    reviewCount: 1600,
    stock: 95,
    category: "Fashion",
    description: "",
    specifications: {},
  },
  {
    id: "prod-030",
    name: "Insulated Travel Tumbler",
    brand: "HydroLife",
    price: 32.99,
    discountPrice: 27.99,
    images: ["https://picsum.photos/seed/tumbler1/600/600"],
    rating: 4.7,
    reviewCount: 2800,
    stock: 130,
    category: "Home & Kitchen",
    description: "",
    specifications: {},
  }
];

export const faqs: Faq[] = [
  {
    id: "faq-1",
    category: "Orders",
    question: "How can I place an order?",
    answer:
      "Browse our products, add the items you want to your cart, and proceed to checkout. Follow the instructions to complete your order.",
  },
  {
    id: "faq-2",
    category: "Orders",
    question: "Can I modify my order after placing it?",
    answer:
      "Orders can only be modified before they are processed. Contact our support team as soon as possible if you need to make a change.",
  },
  {
    id: "faq-3",
    category: "Shipping",
    question: "How long does delivery take?",
    answer:
      "Standard delivery usually takes 3–7 business days, depending on your location and the availability of the products.",
  },
  {
    id: "faq-4",
    category: "Shipping",
    question: "How can I track my order?",
    answer:
      "Once your order has been shipped, you will receive a tracking number. You can use it to check the latest delivery status.",
  },
  {
    id: "faq-5",
    category: "Returns",
    question: "What is your return policy?",
    answer:
      "Eligible products can generally be returned within 30 days of delivery, provided they are unused and in their original condition.",
  },
  {
    id: "faq-6",
    category: "Returns",
    question: "How do I request a refund?",
    answer:
      "Contact our support team with your order details and reason for the return. Once the return is approved, your refund will be processed according to our refund policy.",
  },
  {
    id: "faq-7",
    category: "Payments",
    question: "What payment methods do you accept?",
    answer:
      "We accept major credit and debit cards, UPI, and other payment methods available during checkout.",
  },
  {
    id: "faq-8",
    category: "Payments",
    question: "Is my payment information secure?",
    answer:
      "Yes. Payment information is processed through secure payment providers, and we do not store your complete card details on our servers.",
  },
  {
    id: "faq-9",
    category: "Account",
    question: "How do I create an account?",
    answer:
      "Click the Sign Up or Register option, enter your required details, and follow the instructions to create your account.",
  },
  {
    id: "faq-10",
    category: "Account",
    question: "I forgot my password. What should I do?",
    answer:
      "Click the Forgot Password option on the login page and follow the instructions to reset your password.",
  },
  {
    id: "faq-11",
    category: "Products",
    question: "How can I find a specific product?",
    answer:
      "Use the search bar or browse products by category. You can also use available filters to narrow down the results.",
  },
  {
    id: "faq-12",
    category: "Support",
    question: "How can I contact customer support?",
    answer:
      "You can contact our support team through email or phone. Live chat support will also be available soon.",
  },
];